### ISSUE TITLE
Properties for Configuration for hosted AEM instance

### ISSUE THREAD

**Issue by ahahn95** [Cognifide/gradle-aem-single#16]
Hi,

I have an AEM instance running on AWS, so the .jar and such are not running locally. I was wondering how I should set this up.
<img width="677" alt="Screen Shot 2019-05-14 at 10 56 50 AM" src="https://user-images.githubusercontent.com/15878201/57708261-08893780-7637-11e9-9858-0cddabe92739.png">

**Comment by pun-ky** [comment]
Looks like simple hasn't got updated configuration of this dialog. Look for gradle-aem-multi fork.gradle.kts / gradle.properties.peb file. If you select remote instance type then this jars shouldn't be required. I am quite sure that I fixed already this on multi example. If not, thanks for reporting this issue and I will correct it within few days (I am ooo right now).

Greetings, Krystian

**Comment by pun-ky** [comment]
Maybe @mierzwid could help you sooner.

**Comment by ahahn95** [comment]
@mierzwid That would be great if you could help!

**Comment by pun-ky** [comment]
Regardless this fork configuration you could still just put correct properties into gradle.properties file basing on docs (without running "gradle props" task)

**Comment by pun-ky** [comment]
yep multi updated, single not. 

already fixed but will be available within releasing GAP 7.0.0 next days

**Comment by pun-ky** [comment]
all done. GAP 7 ready. Single updated.

closing as fix applied.
