### ISSUE TITLE
Change quickstart commend in docs

### ISSUE THREAD

**Issue by Gatar** [Cognifide/gradle-aem-single#26]
Please change quickstart commend in docs from: 
`git clone git@github.com:Cognifide/gradle-aem-single.git && cd gradle-aem-single && ./gradlew fork` (SSH)
to:
`git clone https://github.com/Cognifide/gradle-aem-single.git && cd gradle-aem-single && ./gradlew fork` (HTTP)

Cloning repo via ssh ends with error caused by lack of write access:
> git@github.com: Permission denied (publickey).
> fatal: Could not read from remote repository.

Default user intent is clone-only the repository.

**Comment by pun-ky** [comment]
sure, how about creating PR ?:)

**Comment by Gatar** [comment]
Created, also with small improvement in gitignore file :)
https://github.com/Cognifide/gradle-aem-single/pull/27

**Comment by pun-ky** [comment]
thx waiting for more :)
