### ISSUE TITLE
Minor documentation issue

### ISSUE THREAD

**Issue by gruberrolandvaltech** [Cognifide/gradle-aem-single#4]
I think it should be "./gradlew" instead of "gradlew".

https://github.com/Cognifide/gradle-aem-single
https://github.com/Cognifide/gradle-aem-multi

Otherwise, The commands do not work as gradlew is not in path.

**Comment by pun-ky** [comment]
It depends whether you are running it from Git Bash or CMD 😉

**Comment by gruberrolandvaltech** [comment]
Ah, git bash seems to be Windows only. So the command fails on Mac and Linux: "git clone git@github.com:Cognifide/gradle-aem-single.git && cd gradle-aem-single && gradlew fork"

**Comment by pun-ky** [comment]
yep it depends :)
